// import type { Metadata } from "next";
// import {Outfit} from "next/font/google";
// import "./globals.css";
// import Provider from "./provider";
// import { ClerkProvider } from "@clerk/nextjs";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
// const OutFit=Outfit({subsets:['latin']})

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <body className={OutFit.className}>
//         <Provider>
//           {children}
//         </Provider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";

import Provider from "./provider";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "./ConvexClientProvider";

export const metadata: Metadata = {
  title: "Virello",
  description: "Make your trip faster",
};

const OutFit = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={OutFit.className}>
          <ConvexClientProvider>
            <Provider>
              {children}
            </Provider>
          </ConvexClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}